#!/usr/bin/env python3
from pathlib import Path
import argparse
import json
import glob

parser = argparse.ArgumentParser(description='A script to create a json file which will be input to Andrews skimming setup for the nanoAOD files generated by CRAB')
parser.add_argument('--basePath',help="Enter base path of Location of Root Files typivcally till the directory with year_MC/Data without / at the end",required=True)
parser.add_argument('--out',help="enter the full path end with the file name with .json extention")
args = parser.parse_args()



base_path = Path(args.basePath)
searchPhrase = "_13TeV"
listDict = {}
#f = open("fileList.json", "a")
#f.write('{'+'\n')


for dataset in base_path.iterdir():
    if not dataset.is_dir():
        continue
    

    if searchPhrase in dataset.name:
        for name in glob.glob(args.basePath+ '/' + dataset.name+'/*/*/*'):
            keyname = f'{dataset.name[:dataset.name.index(searchPhrase)]}'
            listDict[keyname]=name+"/*.root"


with open(args.out, 'w') as writeFile:
        json.dump(listDict, writeFile, indent=4)

